---
name: Endo | CI checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ci-${{github.ref}}
  cancel-in-progress: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: endo_repo
      POSTGRES_PORT: 5432
    steps:
      - name: Checkout Github repo
        uses: actions/checkout@v3.0.2
      - name: Setup BEAM Env
        uses: erlef/setup-beam@v1.18.2
        with:
          otp-version: 27.0.1
          elixir-version: 1.18.1
      - name: Setup Cache
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ hashFiles('mix.lock') }}-${{ matrix.elixir }}-${{ matrix.otp }}
      - if: steps.mix-cache.outputs.cache-hit != 'true'
        run: mkdir -p priv/plts; mix deps.get; mix deps.compile
      - run: docker compose up -d
      - run: mix lint
      - run: MIX_ENV=test mix do ecto.create, ecto.migrate, test
